### ISSUE TITLE
add support for abstract snippet

### ISSUE THREAD

**Issue by monperrus** [gnieh/bluelatex#210]
the snippet system is great.

if I type abstra <Ctrl-Space>, I'd like to have the snippet

\begin{abstract}

\end{abstract}

**Comment by tdurieux** [comment]
It's already supported.

Snippet list:
- \begin{array}
- \begin{figure}
- \begin{tabular}
- \begin{table}
- \begin{list}
- \begin{enumerate}
- \begin{itemize}
- \begin{frame}
- \begin{abstract}
- \begin{align}
- \begin{align*}
- \begin{equation}
- \begin{equation*}
- \begin{gather}
- \begin{gather*}
- \begin{multline}
- \begin{multline*}
- \begin{split}
- \begin{verbatim}
