### ISSUE TITLE
Deny-of-service with /session

### ISSUE THREAD

**Issue by monperrus** [gnieh/bluelatex#212]
I've just performed an unintentional DOS on bluelatex.

I was testing my backup scripts. I created a lot of tokens without closing them with a DELETE request.

At some points, the server started to stop responding with "503 Service Unavailable, too many sessions"

**Comment by satabin** [comment]
That is a limitation in tiscaf.
The plan is to get rid of tiscaf as soon as possible, so I would say, this won't be fixed.
Session timeout is set by default to 10 minutes (IIRC), but you should work this around by closing sessions you opened.
Also in the next version with spray as HTTP server, the authentication will go a drastically different way, so it probably won't apply to this version.
