### ISSUE TITLE
Unable to permform action, unkown role (capital letter)

### ISSUE THREAD

**Issue by tdurieux** [gnieh/bluelatex#217]
The permissions are mapped with lowercase role but here (
https://github.com/gnieh/bluelatex/blob/c889dc13ad831b9e6e23067c5760f0c4df088ad3/blue-common/src/main/scala/gnieh/blue/http/BlueLet.scala#L263), the server tries to access the permission map with a role which has a capital letter.

**Comment by satabin** [comment]
@tdurieux It should now be fixed, do you confirm?

**Comment by tdurieux** [comment]
I confirm.

**Comment by tdurieux** [comment]
The patch doesn't work on one of my server be work on another server. It's strange, I will investigate.
Sorry, I should have checked it twice.
