### ISSUE TITLE
Demo authentication not working

### ISSUE THREAD

**Issue by MBedex** [gnieh/bluelatex#252]
Hello!

I was trying out the demo a few days ago, and when I went back yesterday, it wasn't working anymore: I can't log in (nor I can sign in).

After little investigation, I found out the ajax call to `https://demo.bluelatex.org/api/session` returns the following error:
>{
>  "name":"unexpected_error",
>  "description":"Something went really wrong. If the problem persists contact an administrator"
>}

I hope it's nothing too bad.

**Comment by tdurieux** [comment]
Hello,

Sorry, the hard disk of the demo server was full...

**Comment by MBedex** [comment]
Thank you very much :)
