### ISSUE TITLE
Server side registration error,

### ISSUE THREAD

**Issue by ntr4ef** [gnieh/bluelatex#254]
Something wrong happened on the server side and the user could not be registered

**Comment by tdurieux** [comment]
On what instance are you working? A custom one or a hosted one (demo.bluelatex, blue.publications.li,...)?

**Comment by ntr4ef** [comment]
Hosted. blue.publications.li

**Comment by ntr4ef** [comment]
![image](https://cloud.githubusercontent.com/assets/6796775/10141470/b6bd4d62-65da-11e5-80f6-845a400be995.png)

**Comment by monperrus** [comment]
Is it fixed now?

**Comment by tdurieux** [comment]
I don't know, I cannot reproduce the bug.

**Comment by ntr4ef** [comment]
Fixed! Thanks!
