### ISSUE TITLE
missing package makeidx

### ISSUE THREAD

**Issue by MahomaIza** [gnieh/bluelatex#258]
Hi

When I try to use \usepackage{makeidx} to create an index of topics, although I do not get any errors, the command \printindex does not produce any page. If I run the same code in my desktop latex it prints the following
![index](https://cloud.githubusercontent.com/assets/19321722/15207550/cbb98dda-17db-11e6-9333-51a9064eec56.jpg)

Could it be that the package is missing? If so, could you add it?

**Comment by tdurieux** [comment]
What server do you use?
blue.publications.li (the server will close at the end of the month)
or demo.bluelatex.org

**Comment by MahomaIza** [comment]
I use demo.bluelatex.org


Mahoma

**Comment by tdurieux** [comment]
As I understand, makeidx requires the use of a external tool to generate the indexes.
@satabin From your point of view, what is the best way to integrate this tool?

makeidx usage:
```bash
makeindex build/main.idx
```

**Comment by satabin** [comment]
A new compiler must be added into \BlueLaTeX to handle `makeindex`. It is quite easy to do I think but requires some testing to make sure that the process sequence is correct.

**Comment by tdurieux** [comment]
Now you can create index on the demo https://demo.bluelatex.org/#/paper/x1c71dd0598854b63

But you need to compile several times the paper in order to see the index table.

**Comment by MahomaIza** [comment]
Awesome!!  Thanks!


Mahoma
