### ISSUE TITLE
My code disappeared

### ISSUE THREAD

**Issue by MahomaIza** [gnieh/bluelatex#260]
I'm using the demo.bluelatex.org server. I can see the compiled pdf but I cannot see the code. 
I've tried accessing a few times, and the code won't show. 
I see an error: main.tex emergency stop

This happened earlier to a friend who is also using bluelatex. 

Thanks

Mahoma

**Comment by tdurieux** [comment]
what is the url of your paper?

Some users report this issue, but we did not found the oriin of the issue (too mush ctrl+z, switch between files, ...).
As you use demo.bluelatex.org I can restore your paper (backup every minutes)

**Comment by MahomaIza** [comment]
Hi Thomas

my url is https://demo.bluelatex.org/#/paper/x7da11afb51ad41c6
I will greatly appreciate if you can restore my paper

It could be switch between files, although I might have switched three or
four times only. Luckily I did have a backup as I was having connectivity
issues a few days ago and I had to work from my computer.

By the way, it's a great project this bluelatex is. Thanks!!


Mahoma

**Comment by tdurieux** [comment]
I restored your paper.

> It could be switch between files
Ok, I will check

> By the way, it's a great project this bluelatex is. Thanks!!
Thanks, unfortunately the project does not evolve since none of the contributors have time to work on it.

**Comment by satabin** [comment]
I’d like to remind everyone that the demo instance is (as mentioned in its name) for demo only, and offers no guarantee on stability or data integrity whatsoever due to the fact that it runs the latest development version which may be highly instable.

Please do not use it for real work, only as a demo.

**Comment by MahomaIza** [comment]
Thanks Lucas

I usually keep a backup, but this time the code disappeared while I was
typing. Normally when I open the file I find that the code is gone.
